export const MAIN_PATH = '/'
export const AUTH_PATH = '/auth'
export const WATCH_PATH = '/watch'
export const CHANNEL_PATH = '/channel'
export const SEARCH_PATH = '/search'
export const STUDIO_PATH = '/studio'